name: Generate Snake Animation

on:
<<<<<<< HEAD
  schedule:
    - cron: "0 */12 * * *"
=======
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

>>>>>>> 05b309cfb53757de305574f7fbf99bad4e57449d
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

<<<<<<< HEAD
      - name: Push Snake Animation to Output Branch
=======
      - name: push snake.svg to the output branch
>>>>>>> 05b309cfb53757de305574f7fbf99bad4e57449d
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

